version: "3.9"
services:
  backend:
    build:
      context: ../backend
    container_name: backend
    env_file: .env
    volumes:
      - ../backend:/app:delegated
      - media:/data/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  worker:
    build:
      context: ../backend
    container_name: worker
    env_file: .env
    volumes:
      - ../backend:/app:delegated
      - media:/data/media
    depends_on:
      - redis
      - db
    command: ["python", "/app/app/worker/worker_runner.py"]

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  media:
